theme: jekyll-theme-minimal
title: Product Management Handbook
description: A white label product management handbook for government digital services
baseurl: /product-management-handbook
google_analytics: <!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-20458896-6"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-20458896-6');
</script>

